// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLib.Models;

public partial class EndedParkedVehicle
{

    public int VehicleId { get; set; }

    public int EndedParkedId { get; set; }

    public string LicensePlate { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Color { get; set; }

    public int NumberOfWheels { get; set; }
    public string Type { get; set; }

    public virtual TimeForEndedVehicle EndedParked { get; set; }
    public EndedParkedVehicle()
    {
        
    }
    public EndedParkedVehicle(string licensePlate, string make, string model, string color, int numberOfWheels, string type, TimeForEndedVehicle endedParked)
    {
        LicensePlate = licensePlate;
        Make = make;
        Model = model;
        Color = color;
        NumberOfWheels = numberOfWheels;
        Type = type;
        EndedParked = endedParked;
    }

}