// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParkingLib.Models;

public partial class TimeForParkedVehicle
{
    public int ActiveParkedId { get; set; }

    public DateTime TimeStarted { get; set; }

    public virtual ICollection<ParkedVehicle> ParkedVehicles { get; set; } = new List<ParkedVehicle>();
    public TimeForParkedVehicle(DateTime timeStarted)
    {
        TimeStarted = timeStarted;
    }
}